Improve manual build process

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -13,7 +13,8 @@ on:
       #- 'feature/**'
       #- '*feature*'
   workflow_dispatch:    # May only be needed to rebuild project when needed
-                        # It has no parent projects
+    branches:           # It has no parent projects
+      - develop
 
 env:
   DISPLAY_CONTEXT: ${{ secrets.DISPLAY_CONTEXT }}    # To display github context for debugging
@@ -29,14 +30,19 @@ jobs:
       #CHILD_YAML: push.yml
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
       - name: Set branch name from github reference
         run: |
           BRANCH_NAME=`basename ${{ github.ref }}`
-          echo "BRANCH_NAME: ${BRANCH_NAME}"
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          if [[ ${BRANCH_NAME} == develop ]]; then
+            echo "BRANCH_NAME: ${BRANCH_NAME}"
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          else
+            echo "Error - Must use the develop branch!"
+            exit 1
+          fi
+
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       #- name: Setup build environment for release branches
       #  if: contains(github.ref,'release')
diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -28,13 +28,22 @@ jobs:
       PHASE_ID: x
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
       - name: Set branch name from github reference
         run: |
           BRANCH_NAME=`basename ${{ github.ref }}`
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          if [[ ${BRANCH_NAME} == *'release_v'* ]]; then
+            echo "Error - Do not use a release branch!"
+            exit 1
+          elif [[ ${BRANCH_NAME} == develop ]]; then
+            echo "Error - Do not use the develop branch!"
+            exit 1
+          else
+            echo "BRANCH_NAME: ${BRANCH_NAME}"
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          fi
+      
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Build the application
         working-directory: build
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,7 +7,9 @@ on:
       - 'release_v*'
       - 'release/release_v*'
   workflow_dispatch:    # May only be needed to rebuild project when needed
-                        # It has no parent projects
+    branches:           # It has no parent projects
+      - 'release_v*'
+      - 'release/release_v*'
 
 env:
   DISPLAY_CONTEXT: ${{ secrets.DISPLAY_CONTEXT }}    # To display github context for debugging
@@ -22,14 +24,19 @@ jobs:
       PHASE_ID: b
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
       - name: Set branch name from github reference
         run: |
           BRANCH_NAME=`basename ${{ github.ref }}`
-          echo "BRANCH_NAME: ${BRANCH_NAME}"
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          if [[ ${BRANCH_NAME} == *'release_v'* ]]; then
+            echo "BRANCH_NAME: ${BRANCH_NAME}"
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          else 
+            echo "ERROR - Must use a release branch!"
+            exit 1
+          fi
+
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Build the application
         working-directory: build
